//go:build go1.22

// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Search packages
	// (GET /internal/packages/search)
	InternalSearchPackages(w http.ResponseWriter, r *http.Request, params InternalSearchPackagesParams)
	// Get packages by search ID
	// (GET /internal/packages/search/{search_id})
	InternalGetPackagesBySearch(w http.ResponseWriter, r *http.Request, searchId string, params InternalGetPackagesBySearchParams)
	// Get failed repositories for a search
	// (GET /internal/packages/search/{search_id}/failed)
	InternalGetFailedRepositories(w http.ResponseWriter, r *http.Request, searchId string)
	// Get package types
	// (GET /internal/packages/types)
	InternalGetPackageTypes(w http.ResponseWriter, r *http.Request)
	// Get projects
	// (GET /internal/projects)
	InternalGetProjects(w http.ResponseWriter, r *http.Request, params InternalGetProjectsParams)
	// Search projects
	// (GET /internal/projects/search)
	InternalSearchProjects(w http.ResponseWriter, r *http.Request, params InternalSearchProjectsParams)
	// Delete project
	// (DELETE /internal/projects/{project_id})
	InternalDeleteProject(w http.ResponseWriter, r *http.Request, projectId int)
	// Get branches
	// (GET /internal/projects/{project_id}/branches)
	InternalGetBranches(w http.ResponseWriter, r *http.Request, projectId int)
	// Create project branch
	// (POST /internal/projects/{project_id}/branches)
	InternalCreateBranch(w http.ResponseWriter, r *http.Request, projectId int)
	// Delete branch
	// (DELETE /internal/projects/{project_id}/branches/{id})
	InternalDeleteBranch(w http.ResponseWriter, r *http.Request, projectId int, id int)
	// Get statistics by projects and packages
	// (GET /internal/statistics)
	InternalStatistics(w http.ResponseWriter, r *http.Request)
	// Kubernetes liveness
	// (GET /kubernetes/live)
	K8sLive(w http.ResponseWriter, r *http.Request)
	// Kubernetes readiness
	// (GET /kubernetes/ready)
	K8sReady(w http.ResponseWriter, r *http.Request)
	// ping
	// (GET /ping)
	Ping(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// InternalSearchPackages operation middleware
func (siw *ServerInterfaceWrapper) InternalSearchPackages(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params InternalSearchPackagesParams

	// ------------- Required query parameter "type" -------------

	if paramValue := r.URL.Query().Get("type"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Required query parameter "query" -------------

	if paramValue := r.URL.Query().Get("query"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "query", r.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InternalSearchPackages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InternalGetPackagesBySearch operation middleware
func (siw *ServerInterfaceWrapper) InternalGetPackagesBySearch(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "search_id" -------------
	var searchId string

	err = runtime.BindStyledParameterWithOptions("simple", "search_id", r.PathValue("search_id"), &searchId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params InternalGetPackagesBySearchParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InternalGetPackagesBySearch(w, r, searchId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InternalGetFailedRepositories operation middleware
func (siw *ServerInterfaceWrapper) InternalGetFailedRepositories(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "search_id" -------------
	var searchId string

	err = runtime.BindStyledParameterWithOptions("simple", "search_id", r.PathValue("search_id"), &searchId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InternalGetFailedRepositories(w, r, searchId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InternalGetPackageTypes operation middleware
func (siw *ServerInterfaceWrapper) InternalGetPackageTypes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InternalGetPackageTypes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InternalGetProjects operation middleware
func (siw *ServerInterfaceWrapper) InternalGetProjects(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params InternalGetProjectsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InternalGetProjects(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InternalSearchProjects operation middleware
func (siw *ServerInterfaceWrapper) InternalSearchProjects(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params InternalSearchProjectsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Required query parameter "query" -------------

	if paramValue := r.URL.Query().Get("query"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "query", r.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InternalSearchProjects(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InternalDeleteProject operation middleware
func (siw *ServerInterfaceWrapper) InternalDeleteProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId int

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InternalDeleteProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InternalGetBranches operation middleware
func (siw *ServerInterfaceWrapper) InternalGetBranches(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId int

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InternalGetBranches(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InternalCreateBranch operation middleware
func (siw *ServerInterfaceWrapper) InternalCreateBranch(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId int

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InternalCreateBranch(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InternalDeleteBranch operation middleware
func (siw *ServerInterfaceWrapper) InternalDeleteBranch(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId int

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InternalDeleteBranch(w, r, projectId, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InternalStatistics operation middleware
func (siw *ServerInterfaceWrapper) InternalStatistics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InternalStatistics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// K8sLive operation middleware
func (siw *ServerInterfaceWrapper) K8sLive(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.K8sLive(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// K8sReady operation middleware
func (siw *ServerInterfaceWrapper) K8sReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.K8sReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ping(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/internal/packages/search", wrapper.InternalSearchPackages)
	m.HandleFunc("GET "+options.BaseURL+"/internal/packages/search/{search_id}", wrapper.InternalGetPackagesBySearch)
	m.HandleFunc("GET "+options.BaseURL+"/internal/packages/search/{search_id}/failed", wrapper.InternalGetFailedRepositories)
	m.HandleFunc("GET "+options.BaseURL+"/internal/packages/types", wrapper.InternalGetPackageTypes)
	m.HandleFunc("GET "+options.BaseURL+"/internal/projects", wrapper.InternalGetProjects)
	m.HandleFunc("GET "+options.BaseURL+"/internal/projects/search", wrapper.InternalSearchProjects)
	m.HandleFunc("DELETE "+options.BaseURL+"/internal/projects/{project_id}", wrapper.InternalDeleteProject)
	m.HandleFunc("GET "+options.BaseURL+"/internal/projects/{project_id}/branches", wrapper.InternalGetBranches)
	m.HandleFunc("POST "+options.BaseURL+"/internal/projects/{project_id}/branches", wrapper.InternalCreateBranch)
	m.HandleFunc("DELETE "+options.BaseURL+"/internal/projects/{project_id}/branches/{id}", wrapper.InternalDeleteBranch)
	m.HandleFunc("GET "+options.BaseURL+"/internal/statistics", wrapper.InternalStatistics)
	m.HandleFunc("GET "+options.BaseURL+"/kubernetes/live", wrapper.K8sLive)
	m.HandleFunc("GET "+options.BaseURL+"/kubernetes/ready", wrapper.K8sReady)
	m.HandleFunc("GET "+options.BaseURL+"/ping", wrapper.Ping)

	return m
}

type InternalSearchPackagesRequestObject struct {
	Params InternalSearchPackagesParams
}

type InternalSearchPackagesResponseObject interface {
	VisitInternalSearchPackagesResponse(w http.ResponseWriter) error
}

type InternalSearchPackages200JSONResponse struct {
	Data PackageSearchResponse `json:"data"`
	Meta MetaResponse          `json:"meta"`
}

func (response InternalSearchPackages200JSONResponse) VisitInternalSearchPackagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type InternalSearchPackages400JSONResponse N400Response

func (response InternalSearchPackages400JSONResponse) VisitInternalSearchPackagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type InternalSearchPackages500JSONResponse N500Response

func (response InternalSearchPackages500JSONResponse) VisitInternalSearchPackagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type InternalGetPackagesBySearchRequestObject struct {
	SearchId string `json:"search_id"`
	Params   InternalGetPackagesBySearchParams
}

type InternalGetPackagesBySearchResponseObject interface {
	VisitInternalGetPackagesBySearchResponse(w http.ResponseWriter) error
}

type InternalGetPackagesBySearch200JSONResponse struct {
	Data PackageSearchResultResponse `json:"data"`
	Meta MetaPaginationResponse      `json:"meta"`
}

func (response InternalGetPackagesBySearch200JSONResponse) VisitInternalGetPackagesBySearchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type InternalGetPackagesBySearch400JSONResponse N400Response

func (response InternalGetPackagesBySearch400JSONResponse) VisitInternalGetPackagesBySearchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type InternalGetPackagesBySearch500JSONResponse N500Response

func (response InternalGetPackagesBySearch500JSONResponse) VisitInternalGetPackagesBySearchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type InternalGetFailedRepositoriesRequestObject struct {
	SearchId string `json:"search_id"`
}

type InternalGetFailedRepositoriesResponseObject interface {
	VisitInternalGetFailedRepositoriesResponse(w http.ResponseWriter) error
}

type InternalGetFailedRepositories200JSONResponse struct {
	Data []FailedRepositoryResponse `json:"data"`
	Meta MetaResponse               `json:"meta"`
}

func (response InternalGetFailedRepositories200JSONResponse) VisitInternalGetFailedRepositoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type InternalGetFailedRepositories500JSONResponse N500Response

func (response InternalGetFailedRepositories500JSONResponse) VisitInternalGetFailedRepositoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type InternalGetPackageTypesRequestObject struct {
}

type InternalGetPackageTypesResponseObject interface {
	VisitInternalGetPackageTypesResponse(w http.ResponseWriter) error
}

type InternalGetPackageTypes200JSONResponse struct {
	Data []PackageTypeResponse `json:"data"`
	Meta MetaResponse          `json:"meta"`
}

func (response InternalGetPackageTypes200JSONResponse) VisitInternalGetPackageTypesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type InternalGetPackageTypes500JSONResponse N500Response

func (response InternalGetPackageTypes500JSONResponse) VisitInternalGetPackageTypesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type InternalGetProjectsRequestObject struct {
	Params InternalGetProjectsParams
}

type InternalGetProjectsResponseObject interface {
	VisitInternalGetProjectsResponse(w http.ResponseWriter) error
}

type InternalGetProjects200JSONResponse struct {
	Data []ProjectResponse      `json:"data"`
	Meta MetaPaginationResponse `json:"meta"`
}

func (response InternalGetProjects200JSONResponse) VisitInternalGetProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type InternalGetProjects400JSONResponse N400Response

func (response InternalGetProjects400JSONResponse) VisitInternalGetProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type InternalGetProjects500JSONResponse N500Response

func (response InternalGetProjects500JSONResponse) VisitInternalGetProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type InternalSearchProjectsRequestObject struct {
	Params InternalSearchProjectsParams
}

type InternalSearchProjectsResponseObject interface {
	VisitInternalSearchProjectsResponse(w http.ResponseWriter) error
}

type InternalSearchProjects200JSONResponse struct {
	Data []ProjectResponse      `json:"data"`
	Meta MetaPaginationResponse `json:"meta"`
}

func (response InternalSearchProjects200JSONResponse) VisitInternalSearchProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type InternalSearchProjects400JSONResponse N400Response

func (response InternalSearchProjects400JSONResponse) VisitInternalSearchProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type InternalSearchProjects500JSONResponse N500Response

func (response InternalSearchProjects500JSONResponse) VisitInternalSearchProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type InternalDeleteProjectRequestObject struct {
	ProjectId int `json:"project_id"`
}

type InternalDeleteProjectResponseObject interface {
	VisitInternalDeleteProjectResponse(w http.ResponseWriter) error
}

type InternalDeleteProject204Response struct {
}

func (response InternalDeleteProject204Response) VisitInternalDeleteProjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type InternalDeleteProject400JSONResponse N400Response

func (response InternalDeleteProject400JSONResponse) VisitInternalDeleteProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type InternalDeleteProject500JSONResponse N500Response

func (response InternalDeleteProject500JSONResponse) VisitInternalDeleteProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type InternalGetBranchesRequestObject struct {
	ProjectId int `json:"project_id"`
}

type InternalGetBranchesResponseObject interface {
	VisitInternalGetBranchesResponse(w http.ResponseWriter) error
}

type InternalGetBranches200JSONResponse struct {
	Data []BranchForProjectResponse `json:"data"`
	Meta MetaResponse               `json:"meta"`
}

func (response InternalGetBranches200JSONResponse) VisitInternalGetBranchesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type InternalGetBranches400JSONResponse N400Response

func (response InternalGetBranches400JSONResponse) VisitInternalGetBranchesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type InternalGetBranches500JSONResponse N500Response

func (response InternalGetBranches500JSONResponse) VisitInternalGetBranchesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type InternalCreateBranchRequestObject struct {
	ProjectId int `json:"project_id"`
	Body      *InternalCreateBranchJSONRequestBody
}

type InternalCreateBranchResponseObject interface {
	VisitInternalCreateBranchResponse(w http.ResponseWriter) error
}

type InternalCreateBranch200JSONResponse struct {
	Data BranchForProjectResponse `json:"data"`
	Meta MetaResponse             `json:"meta"`
}

func (response InternalCreateBranch200JSONResponse) VisitInternalCreateBranchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type InternalCreateBranch400JSONResponse N400Response

func (response InternalCreateBranch400JSONResponse) VisitInternalCreateBranchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type InternalCreateBranch500JSONResponse N500Response

func (response InternalCreateBranch500JSONResponse) VisitInternalCreateBranchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type InternalDeleteBranchRequestObject struct {
	ProjectId int `json:"project_id"`
	Id        int `json:"id"`
}

type InternalDeleteBranchResponseObject interface {
	VisitInternalDeleteBranchResponse(w http.ResponseWriter) error
}

type InternalDeleteBranch204Response struct {
}

func (response InternalDeleteBranch204Response) VisitInternalDeleteBranchResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type InternalDeleteBranch400JSONResponse N400Response

func (response InternalDeleteBranch400JSONResponse) VisitInternalDeleteBranchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type InternalDeleteBranch404JSONResponse N404Response

func (response InternalDeleteBranch404JSONResponse) VisitInternalDeleteBranchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type InternalDeleteBranch409JSONResponse N400Response

func (response InternalDeleteBranch409JSONResponse) VisitInternalDeleteBranchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type InternalDeleteBranch500JSONResponse N500Response

func (response InternalDeleteBranch500JSONResponse) VisitInternalDeleteBranchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type InternalStatisticsRequestObject struct {
}

type InternalStatisticsResponseObject interface {
	VisitInternalStatisticsResponse(w http.ResponseWriter) error
}

type InternalStatistics200JSONResponse struct {
	Data StatisticsResponse `json:"data"`
	Meta MetaResponse       `json:"meta"`
}

func (response InternalStatistics200JSONResponse) VisitInternalStatisticsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type InternalStatistics500JSONResponse N500Response

func (response InternalStatistics500JSONResponse) VisitInternalStatisticsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type K8sLiveRequestObject struct {
}

type K8sLiveResponseObject interface {
	VisitK8sLiveResponse(w http.ResponseWriter) error
}

type K8sLive200Response struct {
}

func (response K8sLive200Response) VisitK8sLiveResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type K8sReadyRequestObject struct {
}

type K8sReadyResponseObject interface {
	VisitK8sReadyResponse(w http.ResponseWriter) error
}

type K8sReady200Response struct {
}

func (response K8sReady200Response) VisitK8sReadyResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PingRequestObject struct {
}

type PingResponseObject interface {
	VisitPingResponse(w http.ResponseWriter) error
}

type Ping200JSONResponse struct {
	Data string       `json:"data"`
	Meta MetaResponse `json:"meta"`
}

func (response Ping200JSONResponse) VisitPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Search packages
	// (GET /internal/packages/search)
	InternalSearchPackages(ctx context.Context, request InternalSearchPackagesRequestObject) (InternalSearchPackagesResponseObject, error)
	// Get packages by search ID
	// (GET /internal/packages/search/{search_id})
	InternalGetPackagesBySearch(ctx context.Context, request InternalGetPackagesBySearchRequestObject) (InternalGetPackagesBySearchResponseObject, error)
	// Get failed repositories for a search
	// (GET /internal/packages/search/{search_id}/failed)
	InternalGetFailedRepositories(ctx context.Context, request InternalGetFailedRepositoriesRequestObject) (InternalGetFailedRepositoriesResponseObject, error)
	// Get package types
	// (GET /internal/packages/types)
	InternalGetPackageTypes(ctx context.Context, request InternalGetPackageTypesRequestObject) (InternalGetPackageTypesResponseObject, error)
	// Get projects
	// (GET /internal/projects)
	InternalGetProjects(ctx context.Context, request InternalGetProjectsRequestObject) (InternalGetProjectsResponseObject, error)
	// Search projects
	// (GET /internal/projects/search)
	InternalSearchProjects(ctx context.Context, request InternalSearchProjectsRequestObject) (InternalSearchProjectsResponseObject, error)
	// Delete project
	// (DELETE /internal/projects/{project_id})
	InternalDeleteProject(ctx context.Context, request InternalDeleteProjectRequestObject) (InternalDeleteProjectResponseObject, error)
	// Get branches
	// (GET /internal/projects/{project_id}/branches)
	InternalGetBranches(ctx context.Context, request InternalGetBranchesRequestObject) (InternalGetBranchesResponseObject, error)
	// Create project branch
	// (POST /internal/projects/{project_id}/branches)
	InternalCreateBranch(ctx context.Context, request InternalCreateBranchRequestObject) (InternalCreateBranchResponseObject, error)
	// Delete branch
	// (DELETE /internal/projects/{project_id}/branches/{id})
	InternalDeleteBranch(ctx context.Context, request InternalDeleteBranchRequestObject) (InternalDeleteBranchResponseObject, error)
	// Get statistics by projects and packages
	// (GET /internal/statistics)
	InternalStatistics(ctx context.Context, request InternalStatisticsRequestObject) (InternalStatisticsResponseObject, error)
	// Kubernetes liveness
	// (GET /kubernetes/live)
	K8sLive(ctx context.Context, request K8sLiveRequestObject) (K8sLiveResponseObject, error)
	// Kubernetes readiness
	// (GET /kubernetes/ready)
	K8sReady(ctx context.Context, request K8sReadyRequestObject) (K8sReadyResponseObject, error)
	// ping
	// (GET /ping)
	Ping(ctx context.Context, request PingRequestObject) (PingResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// InternalSearchPackages operation middleware
func (sh *strictHandler) InternalSearchPackages(w http.ResponseWriter, r *http.Request, params InternalSearchPackagesParams) {
	var request InternalSearchPackagesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InternalSearchPackages(ctx, request.(InternalSearchPackagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InternalSearchPackages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InternalSearchPackagesResponseObject); ok {
		if err := validResponse.VisitInternalSearchPackagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InternalGetPackagesBySearch operation middleware
func (sh *strictHandler) InternalGetPackagesBySearch(w http.ResponseWriter, r *http.Request, searchId string, params InternalGetPackagesBySearchParams) {
	var request InternalGetPackagesBySearchRequestObject

	request.SearchId = searchId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InternalGetPackagesBySearch(ctx, request.(InternalGetPackagesBySearchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InternalGetPackagesBySearch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InternalGetPackagesBySearchResponseObject); ok {
		if err := validResponse.VisitInternalGetPackagesBySearchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InternalGetFailedRepositories operation middleware
func (sh *strictHandler) InternalGetFailedRepositories(w http.ResponseWriter, r *http.Request, searchId string) {
	var request InternalGetFailedRepositoriesRequestObject

	request.SearchId = searchId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InternalGetFailedRepositories(ctx, request.(InternalGetFailedRepositoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InternalGetFailedRepositories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InternalGetFailedRepositoriesResponseObject); ok {
		if err := validResponse.VisitInternalGetFailedRepositoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InternalGetPackageTypes operation middleware
func (sh *strictHandler) InternalGetPackageTypes(w http.ResponseWriter, r *http.Request) {
	var request InternalGetPackageTypesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InternalGetPackageTypes(ctx, request.(InternalGetPackageTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InternalGetPackageTypes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InternalGetPackageTypesResponseObject); ok {
		if err := validResponse.VisitInternalGetPackageTypesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InternalGetProjects operation middleware
func (sh *strictHandler) InternalGetProjects(w http.ResponseWriter, r *http.Request, params InternalGetProjectsParams) {
	var request InternalGetProjectsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InternalGetProjects(ctx, request.(InternalGetProjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InternalGetProjects")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InternalGetProjectsResponseObject); ok {
		if err := validResponse.VisitInternalGetProjectsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InternalSearchProjects operation middleware
func (sh *strictHandler) InternalSearchProjects(w http.ResponseWriter, r *http.Request, params InternalSearchProjectsParams) {
	var request InternalSearchProjectsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InternalSearchProjects(ctx, request.(InternalSearchProjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InternalSearchProjects")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InternalSearchProjectsResponseObject); ok {
		if err := validResponse.VisitInternalSearchProjectsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InternalDeleteProject operation middleware
func (sh *strictHandler) InternalDeleteProject(w http.ResponseWriter, r *http.Request, projectId int) {
	var request InternalDeleteProjectRequestObject

	request.ProjectId = projectId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InternalDeleteProject(ctx, request.(InternalDeleteProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InternalDeleteProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InternalDeleteProjectResponseObject); ok {
		if err := validResponse.VisitInternalDeleteProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InternalGetBranches operation middleware
func (sh *strictHandler) InternalGetBranches(w http.ResponseWriter, r *http.Request, projectId int) {
	var request InternalGetBranchesRequestObject

	request.ProjectId = projectId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InternalGetBranches(ctx, request.(InternalGetBranchesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InternalGetBranches")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InternalGetBranchesResponseObject); ok {
		if err := validResponse.VisitInternalGetBranchesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InternalCreateBranch operation middleware
func (sh *strictHandler) InternalCreateBranch(w http.ResponseWriter, r *http.Request, projectId int) {
	var request InternalCreateBranchRequestObject

	request.ProjectId = projectId

	var body InternalCreateBranchJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InternalCreateBranch(ctx, request.(InternalCreateBranchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InternalCreateBranch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InternalCreateBranchResponseObject); ok {
		if err := validResponse.VisitInternalCreateBranchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InternalDeleteBranch operation middleware
func (sh *strictHandler) InternalDeleteBranch(w http.ResponseWriter, r *http.Request, projectId int, id int) {
	var request InternalDeleteBranchRequestObject

	request.ProjectId = projectId
	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InternalDeleteBranch(ctx, request.(InternalDeleteBranchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InternalDeleteBranch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InternalDeleteBranchResponseObject); ok {
		if err := validResponse.VisitInternalDeleteBranchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InternalStatistics operation middleware
func (sh *strictHandler) InternalStatistics(w http.ResponseWriter, r *http.Request) {
	var request InternalStatisticsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InternalStatistics(ctx, request.(InternalStatisticsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InternalStatistics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InternalStatisticsResponseObject); ok {
		if err := validResponse.VisitInternalStatisticsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// K8sLive operation middleware
func (sh *strictHandler) K8sLive(w http.ResponseWriter, r *http.Request) {
	var request K8sLiveRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.K8sLive(ctx, request.(K8sLiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "K8sLive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(K8sLiveResponseObject); ok {
		if err := validResponse.VisitK8sLiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// K8sReady operation middleware
func (sh *strictHandler) K8sReady(w http.ResponseWriter, r *http.Request) {
	var request K8sReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.K8sReady(ctx, request.(K8sReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "K8sReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(K8sReadyResponseObject); ok {
		if err := validResponse.VisitK8sReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Ping operation middleware
func (sh *strictHandler) Ping(w http.ResponseWriter, r *http.Request) {
	var request PingRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Ping(ctx, request.(PingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Ping")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PingResponseObject); ok {
		if err := validResponse.VisitPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
