// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"time"
)

// N200Response defines model for 200Response.
type N200Response struct {
	Data map[string]interface{} `json:"data"`
	Meta MetaResponse           `json:"meta"`
}

// N400Response defines model for 400Response.
type N400Response struct {
	Error ErrorWithValidationDetailsResponse `json:"error"`
	Meta  MetaResponse                       `json:"meta"`
}

// N404Response defines model for 404Response.
type N404Response struct {
	Error ErrorResponse `json:"error"`
	Meta  *MetaResponse `json:"meta,omitempty"`
}

// N500Response defines model for 500Response.
type N500Response struct {
	Error ErrorWithDetailsResponse `json:"error"`
	Meta  *MetaResponse            `json:"meta,omitempty"`
}

// Branch defines model for Branch.
type Branch struct {
	Name string `json:"name"`
}

// BranchForProjectResponse defines model for BranchForProjectResponse.
type BranchForProjectResponse struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// ErrorDetails defines model for ErrorDetails.
type ErrorDetails struct {
	ErrorId string `json:"error_id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorWithDetailsResponse defines model for ErrorWithDetailsResponse.
type ErrorWithDetailsResponse struct {
	Code    string       `json:"code"`
	Details ErrorDetails `json:"details"`
	Message string       `json:"message"`
}

// ErrorWithValidationDetailsResponse defines model for ErrorWithValidationDetailsResponse.
type ErrorWithValidationDetailsResponse struct {
	Code    string            `json:"code"`
	Details []ValidationError `json:"details"`
	Message string            `json:"message"`
}

// FailedRepositoryResponse defines model for FailedRepositoryResponse.
type FailedRepositoryResponse struct {
	BranchId    int32  `json:"branch_id"`
	BranchName  string `json:"branch_name"`
	Error       string `json:"error"`
	ProjectId   int32  `json:"project_id"`
	ProjectName string `json:"project_name"`
	ProjectUrl  string `json:"project_url"`
	Timestamp   int64  `json:"timestamp"`
}

// MetaPaginationResponse defines model for MetaPaginationResponse.
type MetaPaginationResponse struct {
	LogId      *string            `json:"log_id,omitempty"`
	Pagination PaginationResponse `json:"pagination"`
	Timestamp  time.Time          `json:"timestamp"`
}

// MetaResponse defines model for MetaResponse.
type MetaResponse struct {
	LogId     *string   `json:"log_id,omitempty"`
	Timestamp time.Time `json:"timestamp"`
}

// PackageResponse defines model for PackageResponse.
type PackageResponse struct {
	LastSync time.Time                 `json:"last_sync"`
	Name     string                    `json:"name"`
	Project  ProjectForPackageResponse `json:"project"`

	// ResolvedVersion Resolved version from lockfile (e.g. 1.2.4)
	ResolvedVersion *string `json:"resolved_version,omitempty"`

	// SourceFile Source file name (e.g. composer.lock, package-lock.json)
	SourceFile string `json:"source_file"`

	// VersionConstraint Version constraint from manifest file (e.g. ^1.0.0, ~2.1.0)
	VersionConstraint string `json:"version_constraint"`
}

// PackageSearchResponse defines model for PackageSearchResponse.
type PackageSearchResponse struct {
	SearchId string `json:"search_id"`
}

// PackageSearchResultResponse defines model for PackageSearchResultResponse.
type PackageSearchResultResponse struct {
	Packages []PackageResponse `json:"packages"`

	// RepositoriesLeft Number of repositories left to scan
	RepositoriesLeft int64 `json:"repositories_left"`
	SearchFinished   bool  `json:"search_finished"`

	// Status Current search status (pending, processing, completed)
	Status string `json:"status"`
}

// PackageTypeResponse defines model for PackageTypeResponse.
type PackageTypeResponse struct {
	Label string `json:"label"`
	Name  string `json:"name"`
}

// PaginationResponse defines model for PaginationResponse.
type PaginationResponse struct {
	Limit      int `json:"limit"`
	Page       int `json:"page"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// ProjectForPackageResponse defines model for ProjectForPackageResponse.
type ProjectForPackageResponse struct {
	Branch string `json:"branch"`
	Id     int    `json:"id"`
	Name   string `json:"name"`
	Url    string `json:"url"`
}

// ProjectResponse defines model for ProjectResponse.
type ProjectResponse struct {
	Id           int       `json:"id"`
	Name         string    `json:"name"`
	PackageTypes *[]string `json:"package_types,omitempty"`
	Url          string    `json:"url"`
}

// StatisticsResponse defines model for StatisticsResponse.
type StatisticsResponse struct {
	Packages int64 `json:"packages"`
	Projects int64 `json:"projects"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Field  string `json:"field"`
	Reason string `json:"reason"`
}

// LimitParam defines model for limitParam.
type LimitParam = int

// PageParam defines model for pageParam.
type PageParam = int

// InternalSearchPackagesParams defines parameters for InternalSearchPackages.
type InternalSearchPackagesParams struct {
	// Type Package manager - composer, npm, go, etc
	Type string `form:"type" json:"type"`

	// Query Search by package name and version (optional) - package:version
	Query string `form:"query" json:"query"`
}

// InternalGetPackagesBySearchParams defines parameters for InternalGetPackagesBySearch.
type InternalGetPackagesBySearchParams struct {
	// Page The number of current page.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// InternalGetProjectsParams defines parameters for InternalGetProjects.
type InternalGetProjectsParams struct {
	// Page The number of current page.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// InternalSearchProjectsParams defines parameters for InternalSearchProjects.
type InternalSearchProjectsParams struct {
	// Page The number of current page.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Query Search by project name
	Query string `form:"query" json:"query"`
}

// InternalCreateBranchJSONRequestBody defines body for InternalCreateBranch for application/json ContentType.
type InternalCreateBranchJSONRequestBody = Branch
